name: drawing_app
description: "A drawing board app that has its basic features"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  #description: "Icon pack"
  iconsax: ^0.0.8

  #description: "State management"
  stacked: ^3.4.3

  #description: "Persistent storage"
  shared_preferences: ^2.2.3

  #description: "File system access"
  path_provider: ^2.1.3

  #description: "Save images to gallery"
  gallery_saver: ^2.3.2

  #description: "Unit testing"
  mockito: ^5.0.0
  build_runner: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dart_code_metrics: ^5.7.6

flutter:

  uses-material-design: true