name: drawing_app
description: "A drawing board app that has its basic features"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  #icons
  iconsax: ^0.0.8

  #state management
  stacked: ^3.4.3

  #unit testing
  mockito: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true