name: drawing_app
description: "A drawing board app that has its basic features"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  #description: "Icon pack"
  iconsax: ^0.0.8

  #description: "State management"
  stacked: ^3.4.3

  #description: "Persistent storage"
  shared_preferences: ^2.2.3

  #description: "File system access"
  path_provider: ^2.1.3

  #description: "Save images to gallery"
  gallery_saver: ^2.3.2

  #description: "Unit testing"
  mockito: ^5.0.0
  build_runner: ^2.1.2

  #description: App icon
  flutter_launcher_icons: ^0.13.1

  #description: Splash screen
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dart_code_metrics: ^5.7.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets//images/icon.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  android: true
  ios: true
  color_dark: "#121212"
  image_dark: assets/images/icon.png

  android_12:
    image: assets/images/icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon.png
    icon_background_color_dark: "#121212"

  web: true

flutter:

  uses-material-design: true