name: drawing_app
description:  |
  Drawing App is a feature-rich mobile application designed to provide a seamless and intuitive drawing experience. Whether you're a professional artist, a hobbyist, or someone who loves to doodle, this app offers a wide array of tools and functionalities to cater to your creative needs.
  
  This app is built using Flutter, leveraging its powerful framework to deliver a cross-platform experience on both iOS and Android devices. With an emphasis on performance and user experience, Drawing App aims to be the go-to application for all your drawing needs.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #description: "Icon pack"
  
  iconsax: ^0.0.8
  #description: "Another icon pack"
  
  stacked: ^3.4.3
  #description: "State management"
  
  shared_preferences: ^2.2.3
  #description: "Persistent storage"
  
  path_provider: ^2.1.3
  #description: "File system access"
  
  gallery_saver: ^2.3.2
  #description: "Save images to gallery"
  
  mockito: ^5.0.0
  #description: "Mocking framework for unit tests"

  build_runner: ^2.1.2
  #description: "Code generation tool"

  flutter_launcher_icons: ^0.13.1
  #description: "App icon management"
  
  flutter_native_splash: ^2.4.0
  #description: "Splash screen management"

dev_dependencies:
  flutter_test:
    sdk: flutter
  #description: "Flutter testing framework"

  flutter_lints: ^3.0.0
  #description: "Lint rules for Dart and Flutter"

  dart_code_metrics: ^5.7.6
  #description: "Static code analysis for Dart"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets//images/icon.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  android: true
  ios: true
  color_dark: "#121212"
  image_dark: assets/images/icon.png

  android_12:
    image: assets/images/icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon.png
    icon_background_color_dark: "#121212"

  web: true

flutter:

  uses-material-design: true